name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  publish_job:
    name: Publish the Website
    runs-on: ubuntu-latest
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Hugo
        run: brew install hugo
      - name: Build Website
        run: hugo
      - name: Publish Website
        run: |
          cd public
          git config user.email "michael.collins@neudesic.com"
          git config user.name "Michael Collins"
          git add .
          git commit -m "Publishing commit ${{ github.sha }}"
          git push origin master
