name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  publish_job:
    name: Publish the Website
    runs-on: ubuntu-latest
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v2
      - name: Install Hugo
        run: brew install hugo
      - name: Build Website
        run: hugo
      - name: Publish Website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          externnal_repository: releasemanagerapp/releasemanagerapp.github.io
          user_name: 'Michael Collins'
          user_email: 'michael.collins@neudesic.com'
          commit_message: ${{ github.event.head_commit.message }}
